DESIGN_NAME: vccd1_tie_high
VERILOG_FILES: dir::/../../verilog/rtl/vccd1_tie_high.v
FP_SIZING: absolute
DIE_AREA: [0, 0, 100, 17]
CORE_AREA: [1, 1, 99, 13]
FP_PIN_ORDER_CFG: dir::pin_order.cfg
DIODE_ON_PORTS: out
MAGIC_DEF_LABELS: false

PL_TARGET_DENSITY_PCT: 100
PL_ROUTABILITY_DRIVEN: true
GRT_ADJUSTMENT: 0.12
RT_MAX_LAYER: met3
VDD_NETS:
  - vccd1
GND_NETS:
  - vssd1

FP_IO_VLENGTH: 2
FP_PDN_MULTILAYER: true
FP_PDN_VERTICAL_LAYER: met2
FP_PDN_HORIZONTAL_LAYER: met3
FP_PDN_VWIDTH: 1.6
FP_PDN_HWIDTH: 1.6
FP_PDN_VSPACING: 1.6
FP_PDN_HSPACING: 1.6
FP_PDN_VPITCH: 40
FP_PDN_HPITCH: 12
FP_PDN_VOFFSET: 5
FP_PDN_HOFFSET: 2.48