DESIGN_NAME: mgmt_protect
VERILOG_FILES: dir::/../../verilog/rtl/mgmt_protect.v
FP_SIZING: absolute
DIE_AREA: [0, 0, 220, 60]
CORE_AREA: [2, 2, 218, 58]
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_CFG: dir::pdn.tcl
FALLBACK_SDC_FILE: dir::signoff.sdc
MAX_TRANSITION_CONSTRAINT: 1.5
DIODE_ON_PORTS: both
RSZ_DONT_TOUCH_RX: user
MAGIC_DEF_LABELS: false

PL_TARGET_DENSITY_PCT: 100
PL_ROUTABILITY_DRIVEN: true
GRT_ADJUSTMENT: 0.12
RT_MAX_LAYER: met4
VDD_NETS:
  - vccd0
  - vccd1
GND_NETS:
  - vssd0
  - vssd1

FP_MACRO_HORIZONTAL_HALO: 2
FP_MACRO_VERTICAL_HALO: 2
FP_IO_VLENGTH: 2
FP_PDN_MULTILAYER: false
FP_PDN_VERTICAL_LAYER: met4
FP_PDN_VWIDTH: 1.6
FP_PDN_VSPACING: 1.6
FP_PDN_VPITCH: 40 
FP_PDN_VOFFSET: 5
FP_PDN_HOFFSET: 5
FP_PDN_SKIPTRIM: true

MACROS:
    vccd1_tie_high: 
        gds: dir::../../gds/vccd1_tie_high.gds.gz
        lef: dir::../../lef/vccd1_tie_high.lef
        instances:
            mprj_logic_high_inst: 
                location: [60, 20]
                orientation: N
        nl: dir::../../verilog/gl/vccd1_tie_high.v
        spef:
            min_*: dir::../../spef/multicorner/vccd1_tie_high.min.spef
            nom_*: dir::../../spef/multicorner/vccd1_tie_high.nom.spef
            max_*: dir::../../spef/multicorner/vccd1_tie_high.max.spef
        lib:
            "*": dir::../../lib/vccd1_tie_high.lib
PDN_MACRO_CONNECTIONS: 
    - mprj_logic_high_inst vccd1 vssd1 vccd1 vssd1

EXTRA_EXCLUDED_CELLS: 
  - sky130_fd_sc_hd__and2_2

DESIGN_REPAIR_BUFFER_INPUT_PORTS: false
RUN_POST_GPL_DESIGN_REPAIR: true
RUN_POST_GRT_DESIGN_REPAIR: false
RUN_POST_CTS_RESIZER_TIMING: false
RUN_POST_GRT_RESIZER_TIMING: false
GRT_ALLOW_CONGESTION: true
MAGIC_EXT_USE_GDS: true
LVS_INCLUDE_MARCO_NETLISTS: true
MAGIC_NO_EXT_UNIQUE: true