DESIGN_NAME: gpio_logic_high
VERILOG_FILES: dir::/../../verilog/rtl/gpio_logic_high.v
SYNTH_ELABORATE_ONLY: true
FP_SIZING: absolute
DIE_AREA: [0, 0, 6, 6]
CORE_AREA: [0, 0, 6, 6]
PDN_OBSTRUCTIONS: [met2 -1 -1 1 6]
FP_TAPCELL_DIST: 4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_IO_HLENGTH: 2
PL_TARGET_DENSITY_PCT: 50
GRT_ADJUSTMENT: 0.0
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: false
FP_IO_HLAYER: met1
RT_MAX_LAYER: met2
VDD_NETS:
  - vccd1
GND_NETS:
  - vssd1
FP_PDN_MULTILAYER: false
FP_PDN_VERTICAL_LAYER: met2
FP_PDN_VWIDTH: 1
FP_PDN_VSPACING: 1
FP_PDN_VPITCH: 5
FP_PDN_VOFFSET: 0
FP_PDN_SKIPTRIM: true