DESIGN_NAME: housekeeping
VERILOG_FILES: 
  - dir::/../../verilog/rtl/defines.v
  - dir::/../../verilog/rtl/hk/housekeeping_spi.v
  - dir::/../../verilog/rtl/hk/housekeeping.v

PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc
CLOCK_PORT: ""
CLOCK_NET: "wb_clk_i csclk hk_spi_sck"
SYNTH_STRATEGY: DELAY 0
MAX_FANOUT_CONSTRAINT: 12

FP_SIZING: absolute
DIE_AREA: [0, 0, 300, 300]
FP_CORE_UTIL: 25
FP_ASPECT_RATIO: 1
FP_PIN_ORDER_CFG: dir::pin_order.cfg

FP_PDN_MULTILAYER: false
FP_PDN_CORE_RING: false
FP_PDN_HSPACING: 10
FP_PDN_VPITCH: 80
FP_PDN_HPITCH: 80
FP_PDN_HOFFSET: 5

DIODE_ON_PORTS: both
RSZ_DONT_TOUCH_RX: pad_flashh_clk_buff_inst
MAGIC_DEF_LABELS: false

PL_WIRE_LENGTH_COEF: 0.10
PL_TARGET_DENSITY_PCT: 40
RUN_CTS: true
CTS_SINK_CLUSTERING_SIZE: 40
CTS_SINK_CLUSTERING_MAX_DIAMETER: 120
CTS_CLK_MAX_WIRE_LENGTH: 800
GRT_ADJUSTMENT: 0.12
RT_MAX_LAYER: met4
DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 800
GRT_ALLOW_CONGESTION: true
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
RUN_HEURISTIC_DIODE_INSERTION: true
HEURISTIC_ANTENNA_THRESHOLD: 160

EXTRA_EXCLUDED_CELLS: 
  - sky130_fd_sc_hd__buf_1
