DESIGN_NAME: dll
VERILOG_FILES:
  - dir::/../../verilog/rtl/ahbl_0/clk_rst/dll/dll.v

PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc
CLOCK_PORT: osc
RUN_CTS: false
SYNTH_STRATEGY: DELAY 1
MAX_FANOUT_CONSTRAINT: 14

FP_SIZING: absolute
DIE_AREA: [0, 0, 130, 100]
FP_PIN_ORDER_CFG: dir::pin_order.cfg
TOP_MARGIN_MULT: 2
BOTTOM_MARGIN_MULT: 2

FP_PDN_MULTILAYER: true
FP_PDN_SKIPTRIM: true
FP_PDN_HSPACING: 18.4
FP_PDN_VSPACING: 18.4
FP_PDN_VPITCH: 40
FP_PDN_HPITCH: 40
FP_PDN_HOFFSET: 16.41
FP_PDN_VERTICAL_LAYER: met2
FP_PDN_HORIZONTAL_LAYER: met3

DIODE_PADDING: false
DPL_CELL_PADDING: 2
RSZ_DONT_TOUCH_RX: ringosc|clockp_buffer_0|clockp_buffer_1

PL_TARGET_DENSITY_PCT: 66
GRT_ADJUSTMENT: 0
RT_MAX_LAYER: met3
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
RUN_HEURISTIC_DIODE_INSERTION: true
HEURISTIC_ANTENNA_THRESHOLD: 220

# skip yosys synthesis checks as it fails in the tunable ring osc netlist
ERROR_ON_SYNTH_CHECKS: false
SYNTH_EXCLUDED_CELL_FILE: dir::no_synth.cells