// SPDX-FileCopyrightText: 2020 Efabless Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// SPDX-License-Identifier: Apache-2.0

`timescale 			1ns/1ps
`default_nettype 	none

`ifndef __USER_DEFINES_H
// User GPIO initial configuration parameters
`define __USER_DEFINES_H

// Useful GPIO mode values.  These match the names used in defs.h.
`define GPIO_MODE_MGMT_STD_INPUT_NOPULL    16'h8403
`define GPIO_MODE_MGMT_STD_INPUT_PULLDOWN  16'h8c01
`define GPIO_MODE_MGMT_STD_INPUT_PULLUP    16'h8801
`define GPIO_MODE_MGMT_STD_OUTPUT          16'h9809
`define GPIO_MODE_MGMT_STD_BIDIRECTIONAL   16'h9801

// `define GPIO_MODE_MGMT_STD_ANALOG          16'h000b

`define GPIO_MODE_USER_STD_INPUT_NOPULL    16'h8402
`define GPIO_MODE_USER_STD_INPUT_PULLDOWN  16'h8c00
`define GPIO_MODE_USER_STD_INPUT_PULLUP    16'h8800
`define GPIO_MODE_USER_STD_OUTPUT          16'h9808
`define GPIO_MODE_USER_STD_BIDIRECTIONAL   16'h9800
`define GPIO_MODE_USER_STD_OUT_MONITORED   16'h9802

// `define GPIO_MODE_USER_STD_ANALOG          16'h000a

`define GPIO_ANALOG_TEST 16'h29
// The power-on configuration for GPIO 0 to 7 is fixed and cannot be
// modified (allowing the SPI and debug to always be accessible unless
// overridden by a flash program).

// The values below can be any of the standard types defined above,
// or they can be any 16-bit value if the user wants a non-standard
// startup state for the GPIO.  By default, every GPIO from 8 to 63
// is set to power up as bidir IO controlled by the management SoC.
// Users may want to redefine these so that the user project powers
// up in a state that can be used immediately without depending on
// the management SoC to run a startup program to configure the GPIOs.

`define USER_CONFIG_GPIO_8_INIT  `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_9_INIT  `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_10_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_11_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_12_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_13_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_14_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_15_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_16_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_17_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_18_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_19_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_20_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_21_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_22_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_23_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_24_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_25_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_26_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_27_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_28_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_29_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_30_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_31_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_32_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_33_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_34_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_35_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_36_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_37_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_38_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_39_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_40_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_41_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_42_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_43_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_44_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_45_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_46_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_47_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_48_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_49_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_50_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_51_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_52_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_53_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_54_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_55_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_56_INIT `GPIO_MODE_MGMT_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_57_INIT `GPIO_MODE_MGMT_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_58_INIT `GPIO_MODE_MGMT_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_59_INIT `GPIO_MODE_MGMT_STD_INPUT_PULLDOWN
`define USER_CONFIG_GPIO_60_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_61_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_62_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL
`define USER_CONFIG_GPIO_63_INIT `GPIO_MODE_MGMT_STD_BIDIRECTIONAL

`define USE_USER_VIP
`endif // __USER_DEFINES_H
