###############################################################################
# Created by write_sdc
###############################################################################
current_design vccd1_tie_high
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name __VIRTUAL_CLK__ -period 10.0000 
set_clock_uncertainty 0.2500 __VIRTUAL_CLK__
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[0]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[10]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[11]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[12]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[13]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[14]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[15]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[16]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[17]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[18]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[19]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[1]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[20]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[21]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[22]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[23]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[24]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[25]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[26]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[27]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[28]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[29]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[2]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[30]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[31]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[32]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[33]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[34]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[35]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[36]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[37]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[38]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[39]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[3]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[40]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[41]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[42]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[43]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[44]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[45]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[46]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[47]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[48]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[49]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[4]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[50]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[51]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[52]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[53]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[54]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[55]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[56]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[57]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[58]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[59]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[5]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[60]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[61]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[62]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[63]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[64]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[65]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[66]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[67]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[68]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[69]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[6]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[70]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[71]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[72]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[73]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[74]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[75]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[76]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[77]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[78]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[79]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[7]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[80]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[81]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[82]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[83]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[84]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[85]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[86]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[87]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[88]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[89]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[8]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[90]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {HI[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {HI[90]}]
set_load -pin_load 0.0334 [get_ports {HI[89]}]
set_load -pin_load 0.0334 [get_ports {HI[88]}]
set_load -pin_load 0.0334 [get_ports {HI[87]}]
set_load -pin_load 0.0334 [get_ports {HI[86]}]
set_load -pin_load 0.0334 [get_ports {HI[85]}]
set_load -pin_load 0.0334 [get_ports {HI[84]}]
set_load -pin_load 0.0334 [get_ports {HI[83]}]
set_load -pin_load 0.0334 [get_ports {HI[82]}]
set_load -pin_load 0.0334 [get_ports {HI[81]}]
set_load -pin_load 0.0334 [get_ports {HI[80]}]
set_load -pin_load 0.0334 [get_ports {HI[79]}]
set_load -pin_load 0.0334 [get_ports {HI[78]}]
set_load -pin_load 0.0334 [get_ports {HI[77]}]
set_load -pin_load 0.0334 [get_ports {HI[76]}]
set_load -pin_load 0.0334 [get_ports {HI[75]}]
set_load -pin_load 0.0334 [get_ports {HI[74]}]
set_load -pin_load 0.0334 [get_ports {HI[73]}]
set_load -pin_load 0.0334 [get_ports {HI[72]}]
set_load -pin_load 0.0334 [get_ports {HI[71]}]
set_load -pin_load 0.0334 [get_ports {HI[70]}]
set_load -pin_load 0.0334 [get_ports {HI[69]}]
set_load -pin_load 0.0334 [get_ports {HI[68]}]
set_load -pin_load 0.0334 [get_ports {HI[67]}]
set_load -pin_load 0.0334 [get_ports {HI[66]}]
set_load -pin_load 0.0334 [get_ports {HI[65]}]
set_load -pin_load 0.0334 [get_ports {HI[64]}]
set_load -pin_load 0.0334 [get_ports {HI[63]}]
set_load -pin_load 0.0334 [get_ports {HI[62]}]
set_load -pin_load 0.0334 [get_ports {HI[61]}]
set_load -pin_load 0.0334 [get_ports {HI[60]}]
set_load -pin_load 0.0334 [get_ports {HI[59]}]
set_load -pin_load 0.0334 [get_ports {HI[58]}]
set_load -pin_load 0.0334 [get_ports {HI[57]}]
set_load -pin_load 0.0334 [get_ports {HI[56]}]
set_load -pin_load 0.0334 [get_ports {HI[55]}]
set_load -pin_load 0.0334 [get_ports {HI[54]}]
set_load -pin_load 0.0334 [get_ports {HI[53]}]
set_load -pin_load 0.0334 [get_ports {HI[52]}]
set_load -pin_load 0.0334 [get_ports {HI[51]}]
set_load -pin_load 0.0334 [get_ports {HI[50]}]
set_load -pin_load 0.0334 [get_ports {HI[49]}]
set_load -pin_load 0.0334 [get_ports {HI[48]}]
set_load -pin_load 0.0334 [get_ports {HI[47]}]
set_load -pin_load 0.0334 [get_ports {HI[46]}]
set_load -pin_load 0.0334 [get_ports {HI[45]}]
set_load -pin_load 0.0334 [get_ports {HI[44]}]
set_load -pin_load 0.0334 [get_ports {HI[43]}]
set_load -pin_load 0.0334 [get_ports {HI[42]}]
set_load -pin_load 0.0334 [get_ports {HI[41]}]
set_load -pin_load 0.0334 [get_ports {HI[40]}]
set_load -pin_load 0.0334 [get_ports {HI[39]}]
set_load -pin_load 0.0334 [get_ports {HI[38]}]
set_load -pin_load 0.0334 [get_ports {HI[37]}]
set_load -pin_load 0.0334 [get_ports {HI[36]}]
set_load -pin_load 0.0334 [get_ports {HI[35]}]
set_load -pin_load 0.0334 [get_ports {HI[34]}]
set_load -pin_load 0.0334 [get_ports {HI[33]}]
set_load -pin_load 0.0334 [get_ports {HI[32]}]
set_load -pin_load 0.0334 [get_ports {HI[31]}]
set_load -pin_load 0.0334 [get_ports {HI[30]}]
set_load -pin_load 0.0334 [get_ports {HI[29]}]
set_load -pin_load 0.0334 [get_ports {HI[28]}]
set_load -pin_load 0.0334 [get_ports {HI[27]}]
set_load -pin_load 0.0334 [get_ports {HI[26]}]
set_load -pin_load 0.0334 [get_ports {HI[25]}]
set_load -pin_load 0.0334 [get_ports {HI[24]}]
set_load -pin_load 0.0334 [get_ports {HI[23]}]
set_load -pin_load 0.0334 [get_ports {HI[22]}]
set_load -pin_load 0.0334 [get_ports {HI[21]}]
set_load -pin_load 0.0334 [get_ports {HI[20]}]
set_load -pin_load 0.0334 [get_ports {HI[19]}]
set_load -pin_load 0.0334 [get_ports {HI[18]}]
set_load -pin_load 0.0334 [get_ports {HI[17]}]
set_load -pin_load 0.0334 [get_ports {HI[16]}]
set_load -pin_load 0.0334 [get_ports {HI[15]}]
set_load -pin_load 0.0334 [get_ports {HI[14]}]
set_load -pin_load 0.0334 [get_ports {HI[13]}]
set_load -pin_load 0.0334 [get_ports {HI[12]}]
set_load -pin_load 0.0334 [get_ports {HI[11]}]
set_load -pin_load 0.0334 [get_ports {HI[10]}]
set_load -pin_load 0.0334 [get_ports {HI[9]}]
set_load -pin_load 0.0334 [get_ports {HI[8]}]
set_load -pin_load 0.0334 [get_ports {HI[7]}]
set_load -pin_load 0.0334 [get_ports {HI[6]}]
set_load -pin_load 0.0334 [get_ports {HI[5]}]
set_load -pin_load 0.0334 [get_ports {HI[4]}]
set_load -pin_load 0.0334 [get_ports {HI[3]}]
set_load -pin_load 0.0334 [get_ports {HI[2]}]
set_load -pin_load 0.0334 [get_ports {HI[1]}]
set_load -pin_load 0.0334 [get_ports {HI[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
